In [1]:
import pandas as pd
from collections import defaultdict

from golden_data.config import get_raw_data_path, DATA_INTERIM
from golden_data.custom_field_scan import parse_cf_cell
from golden_data.normalization import load_mapping, normalize_series_with_mapping

In [2]:
raw_path = get_raw_data_path()
df = pd.read_csv(raw_path, low_memory=False)

# Choose an identifier column
id_col_candidates = ["Product ID", "ID", "SKU", "Product Code/SKU"]
id_col = None
for c in id_col_candidates:
    if c in df.columns:
        id_col = c
        break

if id_col is None:
    # Fallback: use index as surrogate ID
    df["RowID"] = df.index
    id_col = "RowID"

id_col

'ID'

In [3]:
rows = []
for _, row in df.iterrows():
    pid = row[id_col]
    for name, value in parse_cf_cell(row.get("Custom Fields")):
        if name in ("Material", "Finish") and value:
            rows.append(
                {
                    id_col: pid,
                    "Field_Name": name,
                    "Raw_Value": str(value),
                }
            )

attr_df = pd.DataFrame(rows)
attr_df.head()

     ID Field_Name      Raw_Value
0  3375   Material  Soft Urethane
1  3376   Material  Soft Urethane
2  3378   Material  Soft Urethane
3  3379   Material  Soft Urethane
4  3380   Material  Soft Urethane

In [4]:
attr_pivot = (
    attr_df
    .pivot_table(index=id_col, columns="Field_Name", values="Raw_Value", aggfunc="first")
    .reset_index()
)

attr_pivot.head()

Field_Name    ID Finish       Material
0           3375    NaN  Soft Urethane
1           3376    NaN  Soft Urethane
2           3378    NaN  Soft Urethane
3           3379    NaN  Soft Urethane
4           3380    NaN  Soft Urethane

In [5]:
from golden_data.normalization import get_mapping_path

material_mapping = load_mapping("Material", normalized_column="normalized_material")
finish_mapping = load_mapping("Finish", normalized_column="normalized_finish")

material_mapping.head(), finish_mapping.head()

(                    raw_value         normalized_material  notes
 0                       Steel                       Steel    NaN
 1  300 SERIES STAINLESS STEEL  300 SERIES STAINLESS STEEL    NaN
 2             Stainless Steel             Stainless Steel    NaN
 3                    Aluminum                    Aluminum    NaN
 4                   Nylon 6/6                   Nylon 6/6    NaN,
                                 raw_value  \
 0  Passivated and/or tested per ASTM A380
 1                                 Natural
 2             Zinc Plate, Bright chromate
 3                             Powder Coat
 4                              Passivated

                         normalized_finish  notes
 0  Passivated and/or tested per ASTM A380    NaN
 1                                 Natural    NaN
 2             Zinc Plate, Bright chromate    NaN
 3                             Powder Coat    NaN
 4                              Passivated    NaN  )

In [6]:
attr_pivot["Material_Normalized"] = normalize_series_with_mapping(
    attr_pivot["Material"],
    material_mapping,
    normalized_column="normalized_material",
    policy="flag",   # flag unmapped values so you can see them
)

attr_pivot["Finish_Normalized"] = normalize_series_with_mapping(
    attr_pivot["Finish"],
    finish_mapping,
    normalized_column="normalized_finish",
    policy="flag",
)

attr_pivot.head(20)

Field_Name    ID Finish       Material Material_Normalized Finish_Normalized
0           3375    NaN  Soft Urethane       Soft Urethane               NaN
1           3376    NaN  Soft Urethane       Soft Urethane               NaN
2           3378    NaN  Soft Urethane       Soft Urethane               NaN
3           3379    NaN  Soft Urethane       Soft Urethane               NaN
4           3380    NaN  Soft Urethane       Soft Urethane               NaN
5           3381    NaN  Soft Urethane       Soft Urethane               NaN
6           3382    NaN  Soft Urethane       Soft Urethane               NaN
7           3383    NaN  Soft Urethane       Soft Urethane               NaN
8           3384    NaN  Soft Urethane       Soft Urethane               NaN
9           3385    NaN  Soft Urethane       Soft Urethane               NaN
10          3386    NaN  Soft Urethane       Soft Urethane               NaN
11          3388    NaN  Soft Urethane       Soft Urethane               NaN
12          3389    NaN  Soft Urethane       Soft Urethane               NaN
13          3392    NaN  Soft Urethane       Soft Urethane               NaN
14          3393    NaN  Soft Urethane       Soft Urethane               NaN
15          3394    NaN  Soft Urethane       Soft Urethane               NaN
16          3395    NaN  Soft Urethane       Soft Urethane               NaN
17          3398    NaN  Soft Urethane       Soft Urethane               NaN
18          3399    NaN  Soft Urethane       Soft Urethane               NaN
19          3400    NaN  Soft Urethane       Soft Urethane               NaN

In [7]:
attr_pivot["Material_Normalized"] = normalize_series_with_mapping(
    attr_pivot["Material"],
    material_mapping,
    normalized_column="normalized_material",
    policy="flag",   # flag unmapped values so you can see them
)

attr_pivot["Finish_Normalized"] = normalize_series_with_mapping(
    attr_pivot["Finish"],
    finish_mapping,
    normalized_column="normalized_finish",
    policy="flag",
)

attr_pivot.head(20)

Field_Name    ID Finish       Material Material_Normalized Finish_Normalized
0           3375    NaN  Soft Urethane       Soft Urethane               NaN
1           3376    NaN  Soft Urethane       Soft Urethane               NaN
2           3378    NaN  Soft Urethane       Soft Urethane               NaN
3           3379    NaN  Soft Urethane       Soft Urethane               NaN
4           3380    NaN  Soft Urethane       Soft Urethane               NaN
5           3381    NaN  Soft Urethane       Soft Urethane               NaN
6           3382    NaN  Soft Urethane       Soft Urethane               NaN
7           3383    NaN  Soft Urethane       Soft Urethane               NaN
8           3384    NaN  Soft Urethane       Soft Urethane               NaN
9           3385    NaN  Soft Urethane       Soft Urethane               NaN
10          3386    NaN  Soft Urethane       Soft Urethane               NaN
11          3388    NaN  Soft Urethane       Soft Urethane               NaN
12          3389    NaN  Soft Urethane       Soft Urethane               NaN
13          3392    NaN  Soft Urethane       Soft Urethane               NaN
14          3393    NaN  Soft Urethane       Soft Urethane               NaN
15          3394    NaN  Soft Urethane       Soft Urethane               NaN
16          3395    NaN  Soft Urethane       Soft Urethane               NaN
17          3398    NaN  Soft Urethane       Soft Urethane               NaN
18          3399    NaN  Soft Urethane       Soft Urethane               NaN
19          3400    NaN  Soft Urethane       Soft Urethane               NaN

In [9]:
from golden_data.data_profiling import profile_raw_data
from golden_data.custom_field_scan import scan_custom_fields
from golden_data.config import DATA_INTERIM
from collections import Counter

import pandas as pd

# 1. Load raw data (optional, but you already do this)
df = profile_raw_data()  # returns full raw DataFrame

# 2. Custom field summary
cf_summary = scan_custom_fields(max_rows=5000)
print("cf_summary rows:", len(cf_summary))

# 3. Phase-1 coverage + value counts (from earlier)
phase1_fields = [
    "Material",
    "Finish",
    "Type",
    "Thread",
    "Length",
    "Diameter",
    "Width",
    "Height",
    "Head Style",
    "RoHS Compliant",
]

from golden_data.config import get_raw_data_path
from golden_data.custom_field_scan import parse_cf_cell

raw_path = get_raw_data_path()
df_raw = pd.read_csv(raw_path, low_memory=False)

if "Item" in df_raw.columns:
    products = df_raw[df_raw["Item"] == "Product"].copy()
else:
    products = df_raw.copy()

total_products = len(products)

field_value_counts = {name: Counter() for name in phase1_fields}
product_has_field = {name: 0 for name in phase1_fields}

for _, row in products.iterrows():
    for name, value in parse_cf_cell(row.get("Custom Fields")):
        if name in phase1_fields and value:
            field_value_counts[name][value] += 1
            product_has_field[name] += 1

coverage_rows = []
for name in phase1_fields:
    cnt = product_has_field[name]
    pct = 100.0 * cnt / total_products if total_products else 0.0
    unique_vals = len(field_value_counts[name])
    coverage_rows.append(
        {
            "Field_Name": name,
            "Products_With_Value": cnt,
            "Coverage_Percent": round(pct, 2),
            "Unique_Values": unique_vals,
        }
    )

coverage_df = pd.DataFrame(coverage_rows).sort_values("Coverage_Percent", ascending=False)

# 4. Top values for Material / Finish
def show_top_values(field_name, top_n=50):
    cnt = field_value_counts[field_name]
    top = cnt.most_common(top_n)
    return pd.DataFrame(top, columns=[f"{field_name}_Value", "Count"])

material_top = show_top_values("Material", top_n=50)
finish_top = show_top_values("Finish", top_n=50)

Profiling raw dataset: /Users/csmiller/projects/bossard-golden-data/data/raw/bossard_raw.csv

Rows: 175917, Columns: 50

                                                 Raw Data Overview
┏━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric        ┃ Value                                                                                           ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Rows          │ 175917                                                                                          │
│ Columns       │ 50                                                                                              │
│ First columns │ Item, ID, Name, Type, SKU, Options, Inventory Tracking, Current Stock, Low Stock, Price, Cost   │
│               │ Price, Retail Price, Sale Price, Brand ID, Channels ...                                         │
└───────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────┘

cf_summary rows: 63

In [10]:
from golden_data.scripts.demo_scan import cf_summary
from golden_data.markdown_utils import df_to_markdown
from golden_data.ai_taxonomist import analyze_custom_fields, summarize_attribute_strategy

# Assume you already have:
# cf_summary, coverage_df, material_top, finish_top

cf_md = df_to_markdown(cf_summary.head(25))
coverage_md = df_to_markdown(coverage_df)
material_md = df_to_markdown(material_top.head(20))
finish_md = df_to_markdown(finish_top.head(20))

detailed_analysis = analyze_custom_fields(cf_md)

strategy_summary = summarize_attribute_strategy(
    cf_md=cf_md,
    coverage_md=coverage_md,
    material_md=material_md,
    finish_md=finish_md,
    mapping_status_notes="""
- Material and Finish top-value lists exported from Notebook 02.
- Initial mapping CSVs created in /mappings for review.
- Normalization helpers in normalization.py ready for Phase 1 pilot.
""",
)

print(detailed_analysis)
print("\n\n================ STRATEGY SUMMARY ================\n\n")
print(strategy_summary)

   Field_Name  Product_Count  Usage_Percent  \
0    Material           2479          49.58
1  Spec Sheet           1975          39.50
2        Type           1506          30.12
3      Length           1437          28.74
4       Color           1297          25.94

                                      Example_Values
0  Steel, Soft Urethane, Nylon 6/6, Polypropylene...
1  <a href=/content/ProductSpecSheets/FCIAMPE0000...
2  Single Row, Vertical, Flexible, Light Weight, ...
3         60 in., 8.000  in., 11 in., 12 in., 75 in.
4                Black, Natural, Bright, White, Gray
### Narrative Overview

The provided BigCommerce custom field export reveals a moderately inconsistent and partially sparse product attribute dataset, posing challenges for Bossard’s 2026 marketing objectives. Several fundamental issues undermine taxonomy standardization, faceted navigation, and AI-driven search capabilities—critical for digital excellence and vertical-specific demand campaigns. Dimension attributes (Lengths, Diameter, Width, etc.) suffer from mixed units and inconsistent formatting; contaminations such as date values inside the Thread field further dilute data quality. Ambiguous field names like “Type,” “Class,” and “Size” create confusion on scope and user intent, damaging SEO clarity and navigation filtering.

Several attributes are underutilized (usage < 20%) or contain overlapping semantic concepts, indicating a need for consolidation or retirement. Material and Finish fields show promising usage and variety but require normalization to unify supplier-specific variants and synonyms, an important prerequisite for co-branding and supplier alignment. Less structured fields with free text and multiple information elements need splitting and controlled vocabularies to improve product findability and sales quoting precision. Overall, a prioritized normalization and governance roadmap will deliver immediate wins for digital shopping experience and set the foundation for dynamic, industry-specific marketing automation.

---

### Issues & Severities by Attribute Group

#### Dimension Attributes (Length, Width, Height, Diameter, Thickness, Outer Diameter (O.D.), Inner Diameter (I.D.))
- **Issues:** Mixed units (inches, mm, mixed textual notes), inconsistent spacing/format (e.g., “0.105 in. Head” vs “7/8 in.”), no clear unit standardization, free text contamination.
- **Severity:** Critical — Blocks faceted navigation, filtering accuracy, automated metadata extraction, and engineering credibility for quoting.
- **Recommendation:**
  - Enforce internal storage in metric (mm) with automated conversion to imperial for frontend.
  - Parse free text to split value and unit into separate atomic fields.
  - Implement validation rules to reject ambiguous or multi-concept values.
  - Establish controlled vocabulary for dimension units and formatting.
  - [Digital Excellence, Sales Alignment]

#### Material & Finish
- **Issues:** Synonyms and supplier-specific variants (e.g., “300 SERIES STAINLESS STEEL,” “Stainless,” “SS”), mixed capitalization and compound entries separated by commas or parenthesis.
- **Severity:** High — Impacts SEO keywords, supplier branding alignment, and vertical-specific marketing segmentation.
- **Recommendation:**
  - Create mapping tables to normalize synonyms and variants (e.g., “300 Series Stainless Steel” → “300 Series Stainless Steel”).
  - Split complex values into primary material and secondary materials if needed (e.g., “Copper Alloy (Contact)” → Material: Copper Alloy; Component: Contact).
  - Enforce controlled vocabulary aligned with industry standards (ASTM, ISO).
  - [Brand Expansion, Industry-Specific Demand Generation, Digital Excellence]

#### Spec Sheet
- **Issues:** Usage under 40%, inconsistent linking syntax with HTML embedded in values, no uniform metadata (e.g., file type or version).
- **Severity:** Medium — Affects user trust and SEO metadata richness but less critical for taxonomy.
- **Recommendation:**
  - Migrate to a dedicated URL field with metadata fields for file type, version, and date.
  - Implement automated extraction of version and date from filename or metadata.
  - [Digital Excellence, Sales Alignment]

#### Thread
- **Issues:** Mixed semantic data — mechanical sizes (#6-32, M5), but also dates (“03/08/2016”), indicating contamination.
- **Severity:** Critical — Misleading metadata hinders automated filtering and quoting, severely impacting sales alignment and search accuracy.
- **Recommendation:**
  - Cleanse data to remove non-thread entries.
  - Standardize thread size using recognized naming conventions (UNC, UNF, Metric ISO).
  - Validate new entries at import.
  - [Digital Excellence, Sales Alignment]

#### Color
- **Issues:** Usage below 30%, mixed generic terms (“Black,” “Bright”) and non-color terms (“Gray”), no controlled vocabulary.
- **Severity:** Medium — Helpful for filter narrowing but not foundational.
- **Recommendation:**
  - Normalize color names to industry color standards (Pantone or RAL).
  - Create controlled list with allowance for N/A or natural color terms.
  - [Digital Excellence]

#### Type, Class, Size, Shape, Head Style
- **Issues:** Ambiguous and overlapping semantic scopes. For example, “Type” contains mixture of form factors and function types. “Class” is vendor-specific and not customer-friendly. “Size” mixes descriptors without clear dimensions.
- **Severity:** High — Difficult to use for SEO, faceted navigation, or vertical targeting.
- **Recommendation:**
  - Define and document precise meanings for each field.
  - Split compound fields where possible (e.g., separate style and function).
  - Retire vendor-specific classifications from public taxonomy or map to industry-standard nomenclature.
  - [Brand Expansion, Digital Excellence, Industry-Specific Demand Generation]

#### RoHS Compliant
- **Issues:** Mixed positive indicators (“yes,” “RoHS Compliant”) and invalid values (“Gray,” “Matte Black”), inconsistent casing and spelling (“Comliant”).
- **Severity:** High — Controls compliance filtering and vertical FDA/medical/defense campaign targeting.
- **Recommendation:**
  - Convert to strict Boolean field with standardized “Yes” or “No” values.
  - Clean invalid entries.
  - [Industry-Specific Demand Generation, Sales Alignment]

#### Installation & Mounting Type
- **Issues:** Low usage (<7%), multiple concepts embedded (installation method + mounting style), inconsistent terms.
- **Severity:** Medium — Useful for engineering decision-making but lower SEO impact.
- **Recommendation:**
  - Split into two fields: Installation Method and Mounting Location/Style.
  - Define and control vocabulary aligned with product engineering specs.
  - [Sales Alignment, Industry-Specific Demand Generation]

#### Access Restriction & Fully Retractable
- **Issues:** Good candidate attributes but low usage (<7%). Some mixed or ambiguous terms.
- **Severity:** Medium — Important for particular verticals (security, defense).
- **Recommendation:**
  - Standardize values and increase usage through governance.
  - [Industry-Specific Demand Generation, Sales Alignment]

---

### Attribute Roadmap

**Phase 1 (0–4 weeks) — Critical / High Normalization Focus**
- Length, Width, Height, Diameter, Thickness, Outer Diameter (O.D.), Inner Diameter (I.D.): Standardize units, parse and validate values, store in atomic fields.
- Thread: Cleanse and normalize sizing conventions; remove contaminations.
- Material & Finish: Normalize synonyms, controlled vocabulary implementation.
- RoHS Compliant: Enforce Boolean field with standardized values.
- Type, Class, Size: Define scope; split or consolidate; retire vendor-specific values.

**Phase 2 (4–12+ weeks) — Medium-Term Improvements & Expansion**
- Spec Sheet: Separate URL and metadata fields; automate metadata extraction.
- Color: Controlled vocabulary aligned with industry standards.
- Installation & Mounting Type: Split and normalize field values.
- Head Style & Shape: Develop mapping tables and controlled list for consistent UI faceting.
- Access Restriction, Fully Retractable: Normalize and increase population.

**Governance Improvements (Long-Term, 12+ weeks)**
- Naming standards for all fields emphasizing clarity by function and engineering relevance.
- Unit standards: Metric internal storage, auto-conversion/display to imperial to support North American market.
- Required fields: Define mandatory attributes per product family to ensure completeness.
- Supplier data onboarding guidelines enforcing controlled vocabularies and validation rules.
- Continuous monitoring and data quality dashboards to track attribute usage and compliance.

**Deprecated / To Be Retired**
- Ambiguous or vendor-specific fields without clear mapping (e.g., certain “Class” values if no industry equivalent).
- Multi-purpose fields mixing concepts without remediation within roadmap timeframe.

---

This structured remediation roadmap with prioritized attribute normalization and governance directly supports Bossard’s pillars:

- Brand Expansion (consistent vocabularies, removal of supplier-specific noise)
- Industry-Specific Demand Generation (vertical-ready attributes like RoHS, Material, Installation)
- Digital Excellence & Marketing Automation (standard units, normalized metadata, faceted nav)
- Sales Alignment & Revenue Impact (engineering-accurate dimensions, quoting credibility, controlled specs)
### Narrative Overview

The provided BigCommerce product export custom fields reveal significant inconsistencies, incompleteness, and semantic ambiguities that pose risks to Bossard’s 2026 marketing pillars, in particular for SEO, faceted navigation, AI search, and sales enablement. Critical issues include widespread unit inconsistency across dimensional fields (Length, Width, Height, Thickness, Diameter), contamination with irrelevant data (dates surfacing in Thread attribute), overloaded fields that mix measurement with descriptive text (Size), and ambiguous attribute labels such as “Type” and “Class” which lack standardized definitions or customer-friendly vocabulary. Additionally, the sparse usage of many fields—often below 20% —suggests either incomplete data entry or non-mandatory field governance, which dilutes filtering capabilities for vertical campaigns or ABM targeting.

The contamination and overlap of values across synonymous or near-duplicate attributes — for example, “Material” vs. potential hidden “Materials” or “Base Material” fields — coupled with non-standard naming conventions, further undermine brand authority and complicate supplier co-marketing alignment. Fields such as “RoHS Compliant” mix values (Yes/No responses) with unexpected colors creating ambiguity, and subjectively named fields like “Class” and “Type” require disambiguation or splitting to separate functional or classification data from form factor descriptors.

Addressing these issues requires a staged roadmap: Phase 1 targeting critical and high-impact normalization of core product identification and dimensional attributes, including unit standardization and controlled vocabulary implementation; Phase 2 focusing on medium-severity, less widely used fields supporting advanced vertical segmentation and sales alignment; and establishing long-term governance rules for attribute naming, units, required fields, and ongoing maintenance. This will enable consistency and scalability across Bossard’s North American catalog aligned with 2026 marketing objectives, improving discoverability, AI usability, sales quoting speed, and brand coherence.

---

### Issues & Severity by Attribute Group

**1. Dimensional Attributes: Length, Width, Height, Diameter, Thickness, Outer Diameter (O.D.), Inner Diameter (I.D.)**
- Issues:
  - Inconsistent units mixed (inches, mm, fractional inches, mix of numerical and text)
  - Free text with unit embedded, e.g. “60 in.”, “0.105 in. Head”
  - Partial or missing values in many products (usage <30%)
- Severity: **Critical** — blocks SEO structured data, faceted navigation, and reliable engineering quoting
- Recommendation:
  - Enforce unit standardization (store all lengths in mm internally)
  - Split composite values into numeric + unit fields
  - Extract structured decimals from fraction or text, enable user-friendly display conversions (inches/mm toggle)
  - For fields like Thickness and Diameter, separate dimension and notes to dedicated “Notes” field
  - Controlled vocabulary for dimensional units (mm, in, cm) [Digital Excellence, Sales Alignment]

**2. Material & Finish**
- Issues:
  - Freeform text mixing base material and composite elements (“Polypropylene (Housing)”)
  - Duplicates or near duplicates possible (Material vs. Materials) and inconsistent casing / synonyms (“steel”, “300 SERIES STAINLESS STEEL”)
  - Finish values inconsistent, mixed with coating descriptions, colors, process terms
- Severity: **High** — impacts brand consistency, supplier alignment, SEO keyword relevance
- Recommendation:
  - Develop comprehensive, industry-standard controlled vocabularies for Material and Finish mapped to supplier catalogs
  - Normalize variants and synonyms (e.g., SS, Stainless → Stainless Steel)
  - Separate composite descriptions (material + location/part) into separate “Material Location” field if needed
  - Implement mapping tables and synonym lists [Brand Expansion, Digital Excellence]

**3. Thread**
- Issues:
  - Contaminated with dates and unrelated values
  - Mixed formats (#6-32, M5, dates)
  - Sparse usage (12%)
- Severity: **Critical** for standard fastener products to enable accurate quoting and search
- Recommendation:
  - Clean contaminated data by filtering invalid entries
  - Use normalized thread size vocabulary (UNC, UNF, Metric ISO)
  - Require validation at ingestion
  - Separate date fields from product attributes [Sales Alignment, Digital Excellence]

**4. Attribute Overload & Ambiguity: Type, Class, Size**
- Issues:
  - “Type” mixes mechanical function, form factor, weight, accessory types
  - “Class” unclear if product family code, industry classification, or internal SKU code
  - “Size” overloaded with descriptive text, dimensional info, standard sizing, units
- Severity: **High** — hinders vertical segmentation, customer filtering, SEO clarity
- Recommendation:
  - Re-engineer “Type” into discrete sub-attributes (e.g., Mechanical Type, Mounting Type, Material Type)
  - Clarify “Class” usage, ideally map to industry-standard classifications or deprecate if internal only
  - Deprecate or split “Size” into Length, Width, Height, or nominal size fields with units
  - Introduce clear field definitions and required validations [Brand Expansion, Industry Demand Generation]

**5. RoHS Compliant**
- Issues:
  - Mixed values: “yes,” “RoHS Compliant,” accidental values like color descriptions
  - Low usage (19%) suggests missing data or inconsistent supplier input
- Severity: **Medium** — important vertical compliance attribute, impacts certain regulated industries
- Recommendation:
  - Normalize to Boolean or standardized “Yes” / “No” / “Unknown” options
  - Enforce supplier data submission standards
  - Use controlled vocabulary for compliance statuses [Industry Demand Generation, Sales Alignment]

**6. Color & Finish**
- Issues:
  - Color overlaps with finish (e.g., “Bright” in both Finish and Color)
  - Non-standard color naming, inconsistent capitalization
- Severity: **Medium**
- Recommendation:
  - Separate Color (pure color) from Finish (surface treatment) explicitly
  - Use controlled color palettes aligned with Pantone or RAL where applicable
  - Normalize synonyms and casing [Brand Expansion, Digital Excellence]

**7. Head Style, Mounting Type, Installation**
- Issues:
  - Semi-structured textual data with mixed detail levels
  - Variations in similar values (“Side/Bracket/Hard” vs “Side/Flat”)
- Severity: **Medium**
- Recommendation:
  - Create controlled vocabularies and allow multi-select or hierarchical attributes
  - Define standard terminologies for mechanical installation parameters [Sales Alignment, Industry Demand Generation]

**8. Other Sparse or Duplicate Fields (Access Restriction, Grip Range, Fully Retractable, Disconnect, Shape)**
- Issues:
  - Sparse usage (<10%) or overlapping semantics exists (e.g., Shape and Head Style)
- Severity: **Low**
- Recommendation:
  - Review for relevance to catalog vertical priorities, consider deprecation or phased data audit
  - Where retained, add clarifying field descriptions and controlled terms [Governance]

---

### Attribute Normalization Roadmap

**Phase 1 (0–4 weeks)** – Critical & High Impact Attributes
- Material (controlled vocabulary, normalized synonyms) [Brand Expansion, Digital Excellence]
- Finish (separate from color, normalize terms) [Brand Expansion]
- Length, Width, Height, Diameter, Thickness (unit standardization, numeric extraction) [Digital Excellence, Sales Alignment]
- Thread (clean data, standardize formats, remove contaminants) [Sales Alignment]
- Type (split and clarify, begin controlled vocabularies) [Brand Expansion, Industry Demand Generation]
- RoHS Compliant (boolean normalization, enforce completeness) [Industry Demand Generation]

**Phase 2 (4–12+ weeks)** – Medium Severity & Sparse Fields
- Color normalization and palette alignment [Brand Expansion]
- Class clarification or deprecation decision [Brand Expansion, Sales Alignment]
- Head Style, Mounting Type, Installation (controlled vocabularies) [Industry Demand Generation]
- Access Restriction, Grip Range, Fully Retractable, Disconnect, Shape (audit and cleanse) [Governance]

**Governance & Long-Term (ongoing)**
- Implement attribute naming conventions and controlled vocabulary standards
- Enforce required fields and data validation on import (units, completeness)
- Maintain mapping tables and synonym dictionaries for materials, finishes, threads, and compliance terms
- Define attribute ownership and update cycles by marketing, engineering, and supplier teams
- Introduce metadata standards for SEO-friendly titles/meta descriptions driven by these normalized attributes [All Pillars]

**Deprecation Candidates**
- “Size” (overloaded and ambiguous, replace with precise dimensions)
- “Class” (unless clarified as industry standard code)
- Any fields with <5% usage and poor data quality after Phase 2 audit

---

This roadmap will ensure Bossard North American BigCommerce catalog data integrity, maximize taxonomy utility for SEO and AI search, enable precise vertical segmentation, and accelerate sales quoting and pipeline attribution—fully aligned with 2026 marketing pillars.


================ STRATEGY SUMMARY ================


**1. Data Quality Snapshot**

- Material (used on ~50% of products) and Finish (~25%) are among the most populated attributes, presenting a strong foundation to build from.
- High-value industrial attributes like Type and Thread feature moderate coverage (~30% and ~12%), but many contain inconsistent free-text variations and missing units.
- Dimensional fields (Length, Width, Height, Diameter) show mixed usage with frequent unit inconsistency and formatting noise, risking poor filter and search accuracy.
- RoHS Compliance and other regulatory or performance-related attributes have low penetration (<20%) and inconsistent value expressions (e.g., "yes," "RoHS Compliant," misspellings).
- Top raw Material and Finish values reveal duplication and inconsistent naming (e.g., "Steel" vs "Carbon Steel," "Passivated" vs "Passivated and/or tested per ASTM A380"), requiring thorough normalization.

**2. Phase 1 Priorities (0–4 weeks)**

1. Develop and finalize normalized mapping tables for Material and Finish, consolidating common synonyms and linking to standardized vocabularies. [Brand Expansion] [Digital Excellence]
